alter table app_users add column tax_set_aside_percent numeric(5,2);
alter table app_users add constraint chk_tax_set_aside_percent
    check (tax_set_aside_percent is null or (tax_set_aside_percent > 0 and tax_set_aside_percent <= 60));

create table tax_payment (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_users(id) on delete cascade,
    tax_year integer not null,
    quarter integer,
    paid_on date not null,
    amount numeric(12,2) not null,
    note varchar(255),
    created_at timestamp(6) with time zone not null,
    constraint chk_tax_payment_amount check (amount > 0),
    constraint chk_tax_payment_quarter check (quarter is null or quarter between 1 and 4)
);

create index idx_tax_payment_owner_year on tax_payment (owner_id, tax_year);
