create table payout_deposit (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_users(id) on delete cascade,
    payout_date date not null,
    amount numeric(12,2) not null,
    note varchar(255),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint uk_payout_deposit_owner_date unique (owner_id, payout_date),
    constraint chk_payout_deposit_amount check (amount >= 0)
);
