create table standing_entry (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_users(id) on delete cascade,
    recorded_on date not null,
    level varchar(16) not null,
    note varchar(255),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint uk_standing_entry_owner_date unique (owner_id, recorded_on),
    constraint chk_standing_entry_level check (level in ('FANTASTIC', 'GREAT', 'FAIR', 'AT_RISK'))
);
