create table app_users (
    id bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    display_name varchar(80) not null,
    email varchar(254) not null unique,
    password_hash varchar(100) not null
);

create table shift (
    id bigint generated by default as identity primary key,
    base_pay numeric(38,2),
    date date,
    end_time time(0),
    start_time time(0),
    tips numeric(38,2),
    owner_id bigint,
    station varchar(255),
    constraint fk_shift_owner foreign key (owner_id) references app_users(id)
);

create index idx_shift_owner_date on shift (owner_id, date);
