create table password_reset_token (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_users(id) on delete cascade,
    token_hash varchar(64) not null,
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    used_at timestamp(6) with time zone,
    constraint uk_password_reset_token_hash unique (token_hash)
);
create index idx_password_reset_token_owner on password_reset_token (owner_id);
