-- Existing accounts count as verified; only new sign-ups start unverified.
alter table app_users add column email_verified boolean not null default true;

-- Short numeric codes sent by email. Only a keyed hash is stored; each code works once, expires, and allows a few
-- wrong tries. The purpose column lets two-factor sign-in reuse the table.
create table email_code (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_users(id) on delete cascade,
    purpose varchar(20) not null,
    code_hash varchar(64) not null,
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    attempts integer not null default 0,
    used_at timestamp(6) with time zone,
    constraint chk_email_code_purpose check (purpose in ('VERIFY_EMAIL'))
);
create index idx_email_code_owner_purpose on email_code (owner_id, purpose);
