-- Optional two-step sign-in: the method, the authenticator secret (encrypted by the app) and the last time step used,
-- so one app code cannot be replayed.
alter table app_users add column two_factor_method varchar(10);
alter table app_users add column totp_secret varchar(255);
alter table app_users add column totp_last_step bigint;
alter table app_users add constraint chk_two_factor_method check (two_factor_method in ('APP', 'EMAIL'));

-- Single-use recovery codes, stored as SHA-256 hashes.
create table recovery_code (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_users(id) on delete cascade,
    code_hash varchar(64) not null,
    created_at timestamp(6) with time zone not null,
    used_at timestamp(6) with time zone
);
create index idx_recovery_code_owner on recovery_code (owner_id);

-- Emailed codes can now also be sign-in codes.
alter table email_code drop constraint chk_email_code_purpose;
alter table email_code add constraint chk_email_code_purpose check (purpose in ('VERIFY_EMAIL', 'SIGN_IN'));
