alter table shift add column miles numeric(8,1);
alter table shift add constraint chk_shift_miles_nonnegative check (miles is null or miles >= 0);

alter table app_users add column mileage_rate numeric(6,3);
alter table app_users add column vehicle_cost_method varchar(20) not null default 'STANDARD_MILEAGE';
alter table app_users add constraint chk_vehicle_cost_method
    check (vehicle_cost_method in ('STANDARD_MILEAGE', 'ACTUAL_EXPENSES'));

create table expense (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_users(id),
    shift_id bigint references shift(id) on delete set null,
    date date not null,
    category varchar(20) not null,
    amount numeric(12,2) not null,
    note varchar(255),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    deleted_at timestamp with time zone,
    delete_batch varchar(36),
    constraint chk_expense_amount_positive check (amount > 0),
    constraint chk_expense_category check (category in ('FUEL', 'TOLL', 'PARKING', 'MAINTENANCE', 'OTHER'))
);

create index idx_expense_owner_date on expense(owner_id, date);
create index idx_expense_owner_deleted on expense(owner_id, deleted_at);
create index idx_expense_shift on expense(shift_id);
