alter table app_users add column time_zone varchar(64) not null default 'America/New_York';
alter table app_users add column calendar_token varchar(64);
alter table app_users add constraint uq_app_users_calendar_token unique (calendar_token);
alter table app_users add column remind_before_minutes integer;
alter table app_users add constraint chk_remind_before_minutes
    check (remind_before_minutes is null or remind_before_minutes in (30, 60, 120, 720));
alter table app_users add column remind_confirm boolean not null default false;

create table push_subscription (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_users(id) on delete cascade,
    endpoint varchar(1024) not null unique,
    p256dh varchar(255) not null,
    auth varchar(255) not null,
    user_agent varchar(255),
    created_at timestamp(6) with time zone not null,
    last_used_at timestamp(6) with time zone
);

create index idx_push_subscription_owner on push_subscription (owner_id);

create table reminder_log (
    shift_id bigint not null references shift(id) on delete cascade,
    kind varchar(20) not null,
    sent_at timestamp(6) with time zone not null,
    primary key (shift_id, kind),
    constraint chk_reminder_log_kind check (kind in ('BEFORE_START', 'CONFIRM'))
);
