spring.application.name=flexbuddy

spring.datasource.url=jdbc:postgresql://localhost:5432/flexbuddy
spring.datasource.username=${DB_USER:flexbuddy}
spring.datasource.password=${DB_PASSWORD:flexbuddy}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
